const saleEndTime = new Date();
saleEndTime.setHours(saleEndTime.getHours() + 17);
const fairlaunchCardData = [
    {
        id: 1,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 2,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 3,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 1,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 2,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 3,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 1,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 2,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 3,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 1,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 2,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 3,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 1,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 2,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 3,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 1,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 2,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 3,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 1,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 2,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 3,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 1,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 2,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 3,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 1,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 2,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 3,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 1,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 2,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 3,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 1,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2",
        launchType: "Fair Launch",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
]

const multiChainCardData = [
    {
        id: 4,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 5,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 6,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 4,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 5,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 6,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 4,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 5,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 6,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 4,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 5,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 6,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 4,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 5,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 6,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 4,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 5,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 6,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 4,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 5,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 6,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 5,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 6,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 4,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 5,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 6,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 4,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 5,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
    {
        id: 6,
        tokenAvatar: "/image/token-image.png",
        status: "upcoming",
        tokenName: "SMB GEN2 multichain",
        launchType: "Multi Chain",
        softCap: "50 SOL",
        progress: {
            value: 50,
            raised: 2420.635,
            percentage: "484.13%",
        },
        liquidity: "60%",
        lockupTime: "🔥 Burned after liquidity is added",
        saleEndsIn: saleEndTime.toLocaleString(),
        tokenInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            name: "Name WAR ON DEVS",
            symbol: "SOLFIN",
            decimals: "9",
            totalSupply: (420000000).toLocaleString(),
        },
        poolInfo: {
            address: "9RFFhhe4XPV8UcBFJkgrDwGGtN3jmktBtw4RBia1bBVn",
            tokensForPresale: (230000000).toLocaleString(),
            tokensForLiquidity: (149000000).toLocaleString(),
            softCap: "5 SOL",
            startTime: "2024.04.05 02:30 (UTC)",
            endTime: "2024.04.05 02:30 (UTC)",
            listingOn: "Raydium AMM V4",
            liquidityPercent: "60%",
            liquidityLockupTime: "Burned after liquidity is added",
        }
    },
]

export { fairlaunchCardData, multiChainCardData }